version: "3.8"
volumes:
  db-store:
services:
  web:
    image: a2ymd/iwt-web
    ports:
      - ${WEB_PORT:-80}:80
    volumes:
      - ${WEB_CONTENT}:/work/backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-laravel_local}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}

  db:
    image: a2ymd/iwt-db
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel_local}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_ROOTPASS:-secret}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=${DB_ROOTPASS:-secret}
    ports:
      - ${PMA_PORT:-8080}:80
    volumes:
      - ./pma_sessions:/sessions
